<?php
return [
    'locales' => [
        'BR' => [
            'name'       => 'Brazil',
            'tld'        => 'com.br',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_BR'),
            'api_key'    => env('AMAZON_API_KEY_BR'),
            'api_secret' => env('AMAZON_API_SECRET_BR'),
        ],
        'CA' => [
            'name'       => 'Canada',
            'tld'        => 'ca',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_CA'),
            'api_key'    => env('AMAZON_API_KEY_CA'),
            'api_secret' => env('AMAZON_API_SECRET_CA'),
        ],
        'CN' => [
            'name'       => 'China',
            'tld'        => 'cn',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_CN'),
            'api_key'    => env('AMAZON_API_KEY_CN'),
            'api_secret' => env('AMAZON_API_SECRET_CN'),
        ],
        'FR' => [
            'name'       => 'France',
            'tld'        => 'fr',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_FR'),
            'api_key'    => env('AMAZON_API_KEY_FR'),
            'api_secret' => env('AMAZON_API_SECRET_FR'),
        ],
        'DE' => [
            'name'       => 'Germany',
            'tld'        => 'de',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_DE'),
            'api_key'    => env('AMAZON_API_KEY_FR'),
            'api_secret' => env('AMAZON_API_SECRET_FR'),
        ],
        'IN' => [
            'name'       => 'India',
            'tld'        => 'in',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_IN'),
            'api_key'    => env('AMAZON_API_KEY_IN'),
            'api_secret' => env('AMAZON_API_SECRET_IN'),
        ],
        'IT' => [
            'name'       => 'Italy',
            'tld'        => 'it',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_IT'),
            'api_key'    => env('AMAZON_API_KEY_IT'),
            'api_secret' => env('AMAZON_API_SECRET_IT'),
        ],
        'JP' => [
            'name'       => 'Japan',
            'tld'        => 'co.jp',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_JP'),
            'api_key'    => env('AMAZON_API_KEY_JP'),
            'api_secret' => env('AMAZON_API_SECRET_JP'),
        ],
        'MX' => [
            'name'       => 'Mexico',
            'tld'        => 'com.mx',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_MX'),
            'api_key'    => env('AMAZON_API_KEY_MX'),
            'api_secret' => env('AMAZON_API_SECRET_MX'),
        ],
        'ES' => [
            'name'       => 'Spain',
            'tld'        => 'es',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_ES'),
            'api_key'    => env('AMAZON_API_KEY_ES'),
            'api_secret' => env('AMAZON_API_SECRET_ES'),
        ],
        'UK' => [
            'name'       => 'United Kingdom',
            'tld'        => 'co.uk',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_UK'),
            'api_key'    => env('AMAZON_API_KEY_UK'),
            'api_secret' => env('AMAZON_API_SECRET_UK'),
        ],
        'US' => [
            'name'       => 'United States',
            'tld'        => 'com',
            'tag'        => env('AMAZON_ASSOCIATE_TAG_US'),
            'api_key'    => env('AMAZON_API_KEY_US'),
            'api_secret' => env('AMAZON_API_SECRET_US'),
        ],
    ],
];
